### ISSUE TITLE
Linting stops after ca. 70 errors

### ISSUE THREAD

**Issue by michalzadkowski** [kungfusheep/SublimeLinter-contrib-stylelint#31]
Not sure what's going on, alas I lack programming background, but from what I see, linting stops about 70 errors in. When I lint directly in CLI, all errors are reported.
I'm attaching a screenshot of ST3 with console opened.
![screen shot 2016-05-09 at 08 49 44](https://cloud.githubusercontent.com/assets/1753010/15107723/af6963e6-15d1-11e6-9e96-1a7f94372e4a.png)
![screen shot 2016-05-09 at 10 30 41](https://cloud.githubusercontent.com/assets/1753010/15107722/af670308-15d1-11e6-9a0f-4bf9c0853ea4.png)

**Comment by ndarville** [comment]
I used to get a similar error in the CLI when I was running certain (ie older) versions of Node.

Although it’s weird that it differs from CLI to the ST3 plug-in, you could try using `n`/`nvm` to test with different versions of Node to see if that makes a difference.

Based on that, it’s very likely the culprit is with stylelint and not this plug-in.

**Comment by michalzadkowski** [comment]
Actually it makes no difference whether I use node 4.4.3 or 6.1.0. Not it Sublime at least. In command line all works perfectly - all errors are reported, and there's no cut-off as in Sublime.
